package org.baldzhiyski.product.mapper;

import org.baldzhiyski.product.model.Product;
import org.baldzhiyski.product.model.req.CreateProductReq;
import org.baldzhiyski.product.model.res.ProductRes;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface ProductMapper {

    // Create entity from request
    @Mapping(target = "id", ignore = true)                // generated by DB
    @Mapping(source = "categoryReq", target = "category") // nested map
    Product toEntity(CreateProductReq req);


    ProductRes toDto(Product product);
}
