spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9099/realms/micro-service


  application:
    name: gateway-service
  config:
    import: optional:configserver:http://${CONFIG_SERVICE_HOST:localhost}:9999