services:

  # === Spring Cloud Config Server ===

  customer-service:
    build:
      context: ./services/customer
      dockerfile: Dockerfile
    container_name: ms_customer_service
    ports:
      - "${CUSTOMER_SERVICE}:8090"
    networks:
      - microservices-net
    restart: unless-stopped
    healthcheck:
      # succeed if TCP + HTTP respond at all (even 404)
      test: [ "CMD-SHELL", "curl -sS -o /dev/null -m 3 http://localhost:8090 || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 40s   # give Spring time to start
    depends_on:
      - mongodb

  config-service:
    build:
      context: ./services/config-service
      dockerfile: Dockerfile
    container_name: ms_config_service
    ports:
      - "${CONFIG_SERVICE_PORT}:9999"
    networks:
      - microservices-net
    restart: unless-stopped
    # healthcheck requires actuator; otherwise keep it simple or remove
    healthcheck:
      # succeed if TCP + HTTP respond at all (even 404)
      test: ["CMD-SHELL", "curl -sS -o /dev/null -m 3 http://localhost:9999 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 40s   # give Spring time to start

  # === Eureka Discovery Server ===
  discovery-service:
    build:
      context: ./services/discovery-service
      dockerfile: Dockerfile
    container_name: ms_discovery_service
    ports:
      - "${DISCOVERY_SERVICE_PORT}:8761"
    networks:
      - microservices-net
    restart: unless-stopped
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8761/ || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 10

  postgresql:
    container_name: ms_pg_sql
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - microservices-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS -o /dev/null -m 3 http://localhost:8761 || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 40s

  zipkin:
    container_name: zipkin
    env_file:
      - .env
    image: openzipkin/zipkin:latest
    ports:
      - "${ZIPKIN_PORT}:9411"
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: mongo_db
    image: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo:/data/db
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - microservices-net
    restart: unless-stopped

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    env_file:
      - .env
    ports:
      - "${MAILDEV_UI_PORT}:1080"
      - "${MAILDEV_SMTP_PORT}:1025"
    networks:
      - microservices-net
    restart: unless-stopped

  rabbitmq:
    container_name: ms_rabbitmq
    image: rabbitmq:3-management
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      - microservices-net
    restart: unless-stopped
    volumes:
      - rabbitmq:/var/lib/rabbitmq

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  mongo:
  rabbitmq:
