spring:
  application:
    name: springone-mcp
  main:
    web-application-type: servlet
    banner-mode: log
  ai:
    mcp:
      server:
        stdio: false
        type: sync
        name: springone-sessions-mcp
        version: 0.0.1
        enabled: true
        instructions: "This server provides session catalog data for SpringOne 2025"

  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: mcp-client
              client-secret: "{noop}secret"
              client-authentication-methods: client_secret_basic
              authorization-grant-types: client_credentials
server:
  port: 8080

logging:
  level:
    org: INFO