spring:
  data:
    mongodb:
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      host: mongodb
      port: ${MONGODB_PORT}
      database: customer
      authentication-database: admin

server:
  port : 8090
