eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka


spring:
  cloud:
    config:
      override.system-properties: false

management:
  zipkin:
    tracing:
      sampling:
        probability: 1.0
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
