eureka:
  instance:
    hostname: discovery-service
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  cloud:
    config:
      override.system-properties: false