eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka


spring:
  cloud:
    config:
      override.system-properties: false