spring:
  data:
    mongodb:
      username: ${MONGO_INITDB_ROOT_USERNAME:baldzhiyski}
      password: ${MONGO_INITDB_ROOT_PASSWORD:baldzhiyski_super_secret}
      host: ${MONGO_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: customer
      authentication-database: admin

server:
  port : 8090
