spring:
  main:
    web-application-type: servlet
    banner-mode: log
  ai:
    mcp:
      server:
        stdio: false
        type: sync
        name: springone-sessions-mcp
        version: 0.0.1
        enabled: true
        instructions: "This server provides needed  endpoints for the E-Commerce-Shop of Hristo Baldzhiyski"
server:
  port: 8999
