spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_AMQP_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:rabbit_user}
    password: ${RABBITMQ_DEFAULT_PASS:rabbit_strong_password}

  mail:
    host: ${MAIL_HOST:localhost}           # MailDev container name
    port: ${MAILDEV_SMTP_PORT:1025}
    username: ${MAIL_USERNAME:}              # MailDev usually blank
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH:false}
      mail.smtp.starttls.enable: ${MAIL_SMTP_STARTTLS:false}
      mail.debug: ${MAIL_DEBUG:false}

app:
  mq:
    exchange: ${APP_EVENTS_EXCHANGE:app.events}
    queues:
      orders: ${APP_QUEUE_ORDERS:notifications.orders}
      payments: ${APP_QUEUE_PAYMENTS:notifications.payments}
      users: ${APP_QUEUE_USERS:notifications.users-actions}


server:
  port: 8777