spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/orders
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8070

application:
  config:
    customer-url: http://api-gateway:8222/api/v1/customers
    product-url: http://api-gateway:8222/api/v1/products
    payment-url: http://api-gateway:8222/api/v1/payments