spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: ${MAIL_HOST:localhost}
    smtp-port: ${MAILDEV_SMTP_PORT:1025}
    web-port: ${MAILDEV_WEB_PORT:1080}   # add this for MailDev web UI


  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_AMQP_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:rabbit_user}
    password: ${RABBITMQ_DEFAULT_PASS:rabbit_strong_password}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/payments
    username: ${POSTGRES_USER:baldzhiyski}
    password: ${POSTGRES_PASSWORD:super_strong_pg_password}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8030

app:
  mq:
    exchange: app.events
stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}   # from Stripe CLI
  success-url: ${STRIPE_SUCCESS_URL:http://localhost:8030/payment/success}
  cancel-url:  ${STRIPE_CANCEL_URL:http://localhost:8030/payment/cancel}
  currency:    ${STRIPE_CURRENCY:EUR}


