spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_AMQP_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:rabbit_user}
    password: ${RABBITMQ_DEFAULT_PASS:rabbit_strong_password}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/payments
    username: ${POSTGRES_USER:baldzhiyski}
    password: ${POSTGRES_PASSWORD:super_strong_pg_password}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8030

app:
  mq:
    exchange: app.events
stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}   # from Stripe CLI
  success-url: ${STRIPE_SUCCESS_URL:http://localhost:8030/demo/success}
  cancel-url:  ${STRIPE_CANCEL_URL:http://localhost:8030/demo/cancel}
  currency:    ${STRIPE_CURRENCY:EUR}